name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      docker-prefix: ${{ steps.docker-tag.outputs.prefix }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout current branch rather than the merge-commit one
          ref: ${{ github.event.head.sha }}
          fetch-depth: 0
      - name: external-repos-changed
        uses: tj-actions/changed-files@v17.2
        id: external-repos-changed
        with:
          sha: ${{ github.event.head.sha }}
          files: |
            .docker/**
      - name: Get docker images tag prefix
        id: docker-tag
        uses: JafarAbdi/docker-tag-prefix-action@main
        with:
          pr_changed_files: ${{ steps.external-repos-changed.outputs.any_changed && github.event_name == 'push' }}
      - run: echo "${{ steps.docker-tag.outputs.prefix }}"
  docker-build-external-repos:
    needs:
      - check-changed-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Testing
        run: echo ${{ needs.check-changed-files.outputs.docker-prefix }}
