name: Build and Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      completed
  pull_request:
  push:

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get docker tag prefix
        id: docker-tag
        uses: JafarAbdi/docker-tag-prefix-action@main
      - run: echo "picknikciuser/moveit-studio:${{ steps.docker-tag.outputs.prefix }}external-repos"
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
