name: Docker Build
on:
  workflow_dispatch:
  push:

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      docker-base: ${{ steps.docker-base.outputs.any_changed }}
      docker: ${{ steps.docker.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
      - name: Check #1
        uses: tj-actions/changed-files@v14.6
        id: docker-base
        with:
          files: |
            .docker/**
      - name: Check #2
        uses: tj-actions/changed-files@v14.6
        id: docker
        with:
          files: |
            .docker/**
            .github/workflows/docker_build.yaml
  docker-build-base:
    needs: check-changed-files
    if: needs.check-changed-files.outputs.docker-base == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker Build Base"
  docker-build-external-repos:
    needs: check-changed-files
    if: needs.check-changed-files.outputs.docker == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get docker tag prefix
        id: docker-tag
        uses: JafarAbdi/docker-tag-prefix-action@main
      - run: echo "picknikciuser/moveit-studio:${{ steps.docker-tag.outputs.prefix}}external-repos"
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  docker-build-moveit-studio:
    runs-on: ubuntu-latest
    needs: docker-build-external-repos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get docker tag prefix
        id: docker-tag
        uses: JafarAbdi/docker-tag-prefix-action@main
      - run: echo "picknikciuser/moveit-studio:${{ steps.docker-tag.outputs.prefix }}moveit-studio"
